services:
  # Backend API
  - type: web
    name: quantity-measurement-api
    runtime: docker
    plan: free # Change to productive if needed
    region: frankfurt # Or your preferred region
    envVars:
      - key: ASPIETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: quantity-db
          property: connectionString
      - key: Redis
        fromService:
          type: redis
          name: quantity-cache
          property: connectionString

databases:
  # Managed PostgreSQL
  - name: quantity-db
    databaseName: quantity_measurement
    user: admin
    plan: free # free tier is available
    region: frankfurt

redis:
  # Managed Redis
  - name: quantity-cache
    plan: free
    region: frankfurt
