services:
  # Backend API
  - type: web
    name: quantity-measurement-api
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: quantity-db
          property: connectionString
      - key: Redis
        fromDatabase:
          name: quantity-cache
          property: connectionString

databases:
  # Managed PostgreSQL
  - name: quantity-db
    databaseName: quantity_measurement
    user: admin
    plan: free
    region: frankfurt

  # Managed Redis (Key Value)
  - name: quantity-cache
    type: keyvalue
    plan: free
    region: frankfurt
